### PR TITLE
Support PATCH for self-referencing entities

### LINKED ISSUE #1301: PATCH fails with self-referencing entity
Trying to work out whether this is a bug or me being an idiot.

Given an entity like:

```
create table website_category (
    id uuid primary key default uuid_generate_v1 ()
    , name text
    , parent_category_id uuid references website_category(id)
);
```

A GET request like `/website_category?id=eq.a9b44532-5cf6-11e9-bad0-0242c0a8f008&select=parent_category(id,name)` works perfectly, returning the nested parent category as expected.

However, the same PATCH, lets say with body `{"name": "new name"}`, fails with:

```
{"message":"Could not find foreign keys between these entities, No relation found between pg_source and parent_category"}
```

This is the first time I've seen this and my app has tonnes of these types of calls that work fine.  This is the first entity I have that references itself, so I'm wondering if that is tripping up Postgrest.

### PR DESCRIPTION
**Pull request by herulume**
Hey
This PR aims to close #1301.

### Code duplication
I know there's a bit of code duplication but I think the `findRelation` function is easier to read this way. 

### Doubt about Relation
I was a bit confused about the `Relation` values in the `findRelation` function. 
When patching from something like `/wc?id=eq.0&select=parent(id, name)`, where `parent_id` refers to another table, say table `xyz`, the relation that is found by `findRelation` has the following:
- relTable name: xyz
- relFTable name: pg_source
- FColumns table name: wc
- relType: Parent

Shouldn't this be `relType: Child`? Since the foreign key is in `wc`. 
I'm pretty sure I'm confusing basic stuff but wanted to clear this. Is there any resource/PR/issue to read more about the `Relation` type?

### CODE REVIEW

**Comment by steve-chavez** [comment]
@herulume Hey!

Hmm. The change you made is not fixing the bug for me.

This is the test that should succeed:

```bash
http PATCH "http://localhost:3000/web_content?id=eq.0&select=name,web_content(name)" "Prefer:return=representation" <<JSON
{"name": "tardis-patched"}
JSON
```
And the response should be:

```json
[{"name":"tardis-patched","web_content":[{"name":"fezz"}]}]
```

Right now the response is:

```
{
    "message": "Could not find foreign keys between these entities, No relation found between pg_source and web_content"
}
```

**Comment by steve-chavez** [comment]
> Is there any resource/PR/issue to read more about the Relation type?

Tbh, that part needs a refactor, definitely not easy to understand. I'm constantly confused by the term Relation since it conflicts with PostgreSQL/Relational Algebra terminology. I think Relationship would've been a better name.

Now, I think this is the first issue regarding the Relation code https://github.com/PostgREST/postgrest/issues/280, from there I'd recommend looking at https://github.com/ruslantalpa/skin, perhaps also ask @ruslantalpa for further explanation.

**Comment by herulume** [comment]
I'm going to investigate further. 
Thank for those links!

**Comment by steve-chavez** [comment]
@herulume Sorry for not being more helpful here.

I've taken some of your work and with that opened #1391.

Basically, `findRelation` wasn't the root cause of the bug since it already worked for self-reference entities. Some tests(for GET) are available here:

https://github.com/PostgREST/postgrest/blob/186381bab29b8dc8e00dafb978f2b8d7830323b8/test/Feature/QuerySpec.hs#L581-L687

The root cause was the `toSourceRelation` function:
https://github.com/PostgREST/postgrest/blob/ae9e27a0c71c6793d998c79141c4bdaccd6edeeb/src/PostgREST/DbRequestBuilder.hs#L95-L105

That's what I ended up modifying to solve the issue in https://github.com/steve-chavez/postgrest/commit/88d64d115ec11588fda0e6741229de5a7574a0c8.

I've added comments to the functions in #1391.  If you have any questions, we can discuss it further there.

**Comment by steve-chavez** [comment]
Superseded by #1391. Thanks for the work done here @herulume.

**Pull request closed without merging**
