### PR TITLE
Update configurator-pg to 0.2.0 (better error messages)

### PR DESCRIPTION
**Pull request by robx**
~~This isn't ready to merge yet given that configurator-pg hasn't been released yet. I'd like to make sure it works for PostgREST before I do that.~~

The new version uses Megaparsec for the low-level file parsing, which results in much less bad error messages. E.g., the example

```
app.settings.external_api_secret = 'some_value'
```

from issue #937 should now result in an error message that's something like

```
Error parsing config file:
    postgrest.conf:1:36:
  |
1 | app.settings.external_api_secret = 'some_value'
  |                                    ^^^^^
unexpected "'some"
expecting "false", "off", "on", "true", '"', '[', or digit
```

instead of the old

```
Error parsing config file:
        parsing support/configs/config: endOfInput
```

I'm not aware of any functional changes (except perhaps that single carriage returns won't work as line terminators any more), but the rewrite was invasive enough and test coverage is limited enough that this should see a bit of testing.

Let me know if it seems to work, and/or if you'd like to see any changes.

### CODE REVIEW

**Comment by robx** [comment]
rebased on updated master, and pulled in minor updates to https://github.com/robx/configurator-pg/pull/8

**Comment by steve-chavez** [comment]
@robx It looks much better! I've tried setting an incorrect value with a single quote at the end:

```bash
jwt-secret = "{\"alg\":\"RS256\",\"kty\":\"RSA\",\"use\":\"sig\",\"n\":\"qcmjboEq-H8UuGlGtjewi83HZyXJ_-1wdmw-QyoHmtabo1ZNn0cH78VYlHcxvAj5BobrHa2Ed6Uyb3r0Y4Vh6NOVtks3-IWGWfTiJAtb5PXKyQLESTJCJgPnNUerYLTU-viEQXnYGz1LmPb3KqFJrUp8FEvqH6FBrHqaVGTa8tvJA5lN6yOURv6z-NALxO5Lko_xBHku33syOUu52wPupK-QKlPdUzh8NRIOLny8RVumUs_GXm76lKiBCH3QNxzSRCJb4b5JF-vr5CIAW-S9nUM6u4cBnNMci7FSxP5GS1mx0Z4InUFDhOlWShxCGnr0dN5RHNL3i6pK3JLJmWWU9Q\",\"kid\":\"RTEyMDNCQUJDMUFGNUQyQ0YwRTk2M0Q0OTFGNDdBMDU4RTlERUM2MA\",\"e\":\"AQAB\"}"'
```
And the error message is pretty clear(even showing the line number):
```
Error parsing config file:
support/configs/config-robx:15:502:
   |
15 | jwt-secret = "{\"alg\":\"RS256\",\"kty\":\"RSA\",\"use\":\"sig\",\"n\":\"qcmjboEq-H8UuGlGtjewi83HZyXJ_-1wdmw-QyoHmtabo1ZNn0cH78VYlHcxvAj5BobrHa2Ed6Uyb3r0Y4Vh6NOVtks3-IWGWfTiJAtb5PXKyQLESTJCJgPnNUerYLTU-viEQXnYGz1LmPb3KqFJrUp8FEvqH6FBrHqaVGTa8tvJA5lN6yOURv6z-NALxO5Lko_xBHku33syOUu52wPupK-QKlPdUzh8NRIOLny8RVumUs_GXm76lKiBCH3QNxzSRCJb4b5JF-vr5CIAW-S9nUM6u4cBnNMci7FSxP5GS1mx0Z4InUFDhOlWShxCGnr0dN5RHNL3i6pK3JLJmWWU9Q\",\"kid\":\"RTEyMDNCQUJDMUFGNUQyQ0YwRTk2M0Q0OTFGNDdBMDU4RTlERUM2MA\",\"e\":\"AQAB\"}"'
   |

                                                                                          ^
unexpected '''
expecting end of input or end of line
```

**Comment by steve-chavez** [comment]
I've yet to find a failure test case. It is looking pretty solid and the `io-tests.sh` are passing.

**Comment by robx** [comment]
Thanks for checking! I've released version 0.2.0 now, and changed this PR to pull that in.

Still happy to fix any issues that show up with this change of course.

**Comment by steve-chavez** [comment]
@robx Cool! 

Should I merge this with the `0.2.0` version? I've just seen you released [0.2.1](https://github.com/robx/configurator-pg/commit/886ec303fe1d2a0ae23db99d5dc87ee1344b1b60).

**Comment by robx** [comment]
It should be fine to merge as is. 0.2.1 just adds test resource files to the dist tarball that I forgot, which caused test failures on stackage. That shouldn't affect use of configurator-pg as a dependency.

**Pull request merged**
