### PR TITLE
Work around macos case sensitivity issue

### PR DESCRIPTION
**Pull request by robx**
See also https://github.com/haskell/cabal/issues/4739.

### CODE REVIEW

**Comment by robx** [comment]
@steve-chavez The offending macos build is only triggered on tags I suppose?

**Comment by robx** [comment]
This fixes the macos travis release build error: https://travis-ci.org/robx/postgrest/builds/550137527 (still fails because my postgrest travis isn't set up for release upload)

**Comment by robx** [comment]
The circleci failure in build-test-11 is the one fixed by #1331. The circleci failure in build-prof-test looks like the one we saw before when building with ghc 8.6.5, an apparent out of memory issue while compiling postgrest. It seems unlikely but not impossible that this was directly caused by this change. Perhaps it's because everything needs to be recompiled for the change in GHC options?

**Comment by steve-chavez** [comment]
@robx Actually travis(osx build) was triggered on every push to master. It builds dependencies for a limited time(`gtimeout 1800`) to not surpass the travis max build time and err. It's an ugly workaround that was working until now to build releases for osx.
 
> Perhaps it's because everything needs to be recompiled for the change in GHC options

Yes. That happens when compiling with profiling enabled. Not sure why.

**Pull request merged**
