### PR TITLE
[WIP] Fix #1360, fix unique foreign key in view.

### LINKED ISSUE #1360: Foreign key not detected on view + unique
### Environment

* PostgreSQL version: docker `postgres:latest` (`53912975086f` / `11.4`)
* PostgREST version: docker `postgrest/postgrest:latest` (`75eddc43eae5` / `v6.0.0`)
* Operating system: docker host `debian:buster`, PostgREST container `debian:stretch-slim`

### Description of issue

```bash
docker-compose exec db psql -U postgres app
```
executing:
```sql
CREATE SCHEMA private;
CREATE TABLE private.aaa (link INT NOT NULL UNIQUE);
CREATE TABLE private.bbb (link INT REFERENCES private.aaa(link) NOT NULL);
CREATE VIEW public.aaa AS SELECT * FROM private.aaa;
CREATE VIEW public.bbb AS SELECT * FROM private.bbb;
```
followed by a reload/restart:
```bash
docker-compose restart api
```

Swagger UI output:
swagger UI showing no Foreign Key relationship

Checking OpenAPI JSON:
```bash
curl -s "http://localhost:3030/" | jq '.definitions'
```
```js
{
  "aaa": {
    "properties": {
      "link": {
        "format": "integer",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "bbb": {
    "properties": {
      "link": {
        "format": "integer",
        "type": "integer"
      }
    },
    "type": "object"
  }
}
```

#### Expected:
If we use the `public` schema to create the tables or use a `PRIMARY KEY` instead of `UNIQUE` we do get a proper foreign key, correct output (minus the `PRIMARY KEY` note):

swagger UI showing a Foreign Key relationship if `PRIMARY KEY` is used

```js
{
  "aaa": {
    "properties": {
      "link": {
        "format": "integer",
        "type": "integer",
        "description": "Note:\nThis is a Primary Key.<pk/>"
      }
    },
    "type": "object"
  },
  "bbb": {
    "properties": {
      "link": {
        "format": "integer",
        "type": "integer",
        "description": "Note:\nThis is a Foreign Key to `aaa.link`.<fk table='aaa' column='link'/>"
      }
    },
    "type": "object"
  }
}
```

#### Debug:
Output for both `PRIMARY KEY` and `UNIQUE` setup for all relevant SQL queries in [`DbStructure.hs`](https://github.com/PostgREST/postgrest/blob/c37a9f5ec370a51a50bdd4120bfc6ef78d964648/src/PostgREST/DbStructure.hs):
```sql
-- allSynonyms
 table_schema | table_name | table_column_name | view_schema | view_name | view_colum_name 
--------------+------------+-------------------+-------------+-----------+-----------------
 private      | aaa        | link              | public      | aaa       | link
 private      | bbb        | link              | public      | bbb       | link

-- allChildRelations output:
 table_schema | table_name | columns | foreign_table_schema | foreign_table_name | foreign_columns 
--------------+------------+---------+----------------------+--------------------+-----------------
 private      | bbb        | {link}  | private              | aaa                | {link}

-- allPrimaryKeys output (empty for UNIQUE setup):
 table_schema | table_name | column_name 
--------------+------------+-------------
 private      | aaa        | link

-- allColumns output (in PRIMARY KEY case):
 schema  | table_name | name | description | position | nullable | col_type | updatable | max_len | precision | default_value | enum 
---------+------------+------+-------------+----------+----------+----------+-----------+---------+-----------+---------------+------
 private | aaa        | link |             |        1 | f        | integer  | t         |         |        32 |               | 
 private | bbb        | link |             |        1 | f        | integer  | t         |         |        32 |               | 
 public  | aaa        | link |             |        1 | t        | integer  | t         |         |        32 |               | 
 public  | bbb        | link |             |        1 | t        | integer  | t         |         |        32 |               | 

-- allColumns output (in UNIQUE case):
 schema  | table_name | name | description | position | nullable | col_type | updatable | max_len | precision | default_value | enum 
---------+------------+------+-------------+----------+----------+----------+-----------+---------+-----------+---------------+------
 private | bbb        | link |             |        1 | f        | integer  | t         |         |        32 |               | 
 public  | aaa        | link |             |        1 | t        | integer  | t         |         |        32 |               | 
 public  | bbb        | link |             |        1 | t        | integer  | t         |         |        32 |               | 

-- allTables output:
 table_schema | table_name | table_description | insertable 
--------------+------------+-------------------+------------
 private      | aaa        |                   | t
 private      | bbb        |                   | t
 public       | aaa        |                   | t
 public       | bbb        |                   | t

-- accessibleTables output:
 table_schema | table_name | table_description | insertable 
--------------+------------+-------------------+------------
 public       | aaa        |                   | t
 public       | bbb        |                   | t
```

So it's probably in the `allColumns` SQL query, if this misses the `private.aaa.link` it will fail to link it later on.

_**Update 1:**_
That the `PRIMARY KEY` and tables in the `public` schema do work definitely has something to do with this condition:
https://github.com/PostgREST/postgrest/blob/c37a9f5ec370a51a50bdd4120bfc6ef78d964648/src/PostgREST/DbStructure.hs#L529

_**Update 2:**_
Adding `'u'` [see `pg_constraint` Columns `contype`](https://www.postgresql.org/docs/current/catalog-pg-constraint.html#id-1.10.4.15.6) might solve the problem, at least it gives the same output for the `allColumns` query, the `'u'`is to be added here:
https://github.com/PostgREST/postgrest/blob/c37a9f5ec370a51a50bdd4120bfc6ef78d964648/src/PostgREST/DbStructure.hs#L423

My basic `docker-compose.yml`:
```yml
version: '3'
services:
  api:
    image: postgrest/postgrest
    ports:
      - "3030:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://postgres:password@db:5432/app
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - db
  db:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      API_URL: http://localhost:3030/
```

### PR DESCRIPTION
**Pull request by bwbroersma**
_Disclaimer: I did not the tests_
Fix #1360.

### CODE REVIEW

**Comment by steve-chavez** [comment]
@bwbroersma Thanks for jumping into the code!

From a quick glance the fix makes sense, though we would need a test to corroborate.
Btw, the failing test suite(build-prof-test) is unrelated, no problem about that.

Doing the test would be basically adding the fixures here in [schema.sql](https://github.com/PostgREST/postgrest/blob/master/test/fixtures/schema.sql) and adding the test in 
[StructureSpec.hs](https://github.com/PostgREST/postgrest/blob/master/test/Feature/StructureSpec.hs).

**Comment by bwbroersma** [comment]
I agree, although I have a strong feeling this is the correct fix. My other enum fix was probably the wrong approach. But I will look into creating some tests for it.

For now we are using our own [PostgREST OpenState 'fork'](https://github.com/openstate/postgrest/tree/openstate) with my PRs merged in production, but the goal is be on PostgREST stable releases of course. BTW I didn't see any docker development documentation, the approach seems to be to install stack locally? Since we try to dockerize all the things (also development) [I wrote the minimal steps to build the docker image  for our fork](https://github.com/openstate/allmanak/#custom-postgrest-in-v1).

**Comment by steve-chavez** [comment]
@bwbroersma I also think your fix is correct. So I've added tests for it on #1395!

I wasn't able to push on this branch, let me know if you have any thoughts on the other PR.

**Comment by steve-chavez** [comment]
Closing since #1395 got merged. Thank you @bwbroersma.

**Pull request closed without merging**
