### PR TITLE
switch to buster base

### PR DESCRIPTION
**Pull request by pixie79**
Updated the base image to buster - https://github.com/PostgREST/postgrest/issues/1260

### CODE REVIEW

**Comment by steve-chavez** [comment]
Buster doesn't seem to be stable https://www.debian.org/releases/buster/index.en.html.

I think we should stick to LTS releases listed here https://wiki.debian.org/LTS.

So `stretch` would be the best choice.

**Comment by pixie79** [comment]
I considered that, stretch also has a lot of CVEs too. 
Might check CentOS and see if there base is better

**Comment by steve-chavez** [comment]
CentOS would change almost all the Dockerfile. 

What are the CVEs you're concerned about? Are you sure they would affect us?

**Comment by steve-chavez** [comment]
Switching to `stretch-slim` would be a good idea. A while ago I got a `Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found` when trying to build the image. It seems debian changed jessie mirror urls recently:

  - https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
  - https://stackoverflow.com/questions/55386246/w-failed-to-fetch-http-deb-debian-org-debian-dists-jessie-updates-main-binary
  - https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

**Comment by steve-chavez** [comment]
Closing since https://github.com/PostgREST/postgrest/pull/1297 got merged.

**Pull request closed without merging**
