### PR TITLE
Nix development and build environment

### PR DESCRIPTION
**Pull request by monacoremo**
Work in progress towards #756 

## Tasks

* [x] `nix-build` works, building PostgREST with Nix
* [x] `nix-shell` development environment
  * [x] includes a Nix development environment for PostgREST (`ghc` etc.) 
  * [x] `cabal` integrated with ghc (build, test etc.)
  * [x] `cabal build` works
  * [x] Testing
    * [x] `postgrest-test-spec` implemented, runs the test suite against a temporary db
    * [x] Pass all tests
    * [x] `postgrest-test-spec-all`: implement a script for running the tests against all Postgres versions
    * [x] integrate other test scripts
      * [x] `io-tests.sh`
      * [x] `memory-tests.sh`
  * [x] Styling: implemented `postgrest-style`, automatically formats Haskell and Nix code so far
  * [x] Linting: implemented `postgrest-lint`, uses `hlint` so far
  * [x] Pinned nixpkgs: implemented `nixpkgs-upgrade`, a script for upgrading the pinned version of nixpkgs to the current nixpkgs-unstable
  
## Possibly for later, tdb

* Docs on postgrest-docs
* CI integration
  * [x] Preferences regarding CircleCI, Github Actions, etc.? --> CircleCI
  * Caching with Cachix (tdb if required, as we track nixpkgs-unstable and most packages have cached builds)
* Static: building static binaries directly from Nix  
* Docker: generate Docker images directly from Nix
* Cleanup of older setup?
  * determine how much should be possible to do without Nix (build, run test suite, lint, ...)
  * `test/`: create_test_db, destroy_test_db etc.
  * Makefile
  * CI
  * `docker/`

### CODE REVIEW

**Comment by monacoremo** [comment]
@steve-chavez was there a special reason for the lower bound on https://github.com/PostgREST/postgrest/blob/f6ce93f2c83178327ae42e5da42dd92a3f3742e2/test/QueryCost.hs#L53 ? This repeatedly broke the tests with `test/QueryCost.hs:53:13: 1) QueryCost, call proc query, params=multiple-objects, should not exceed cost when calling setof composite proc predicate failed on: Nothing`

**Comment by steve-chavez** [comment]
@monacoremo The problem is that `(Nothing < Just 2000) == True`. I left the lower bound as a way to check that `cost` is not giving `Nothing`, because `(Nothing > Just 2000) == False`. This definitely needs refactoring.

So as it is, the QueryCost module is not really working because `cost` is `Nothing`.

**Comment by steve-chavez** [comment]
Regarding CI, I think we should stick with CircleCI. I remember begriffs got us a deal with them for extra resources usage. IIRC I think they increased timeout for builds and enabled building on OSX(we're not taking advantage of this).

Integrating static binary building on CI would be nice. But I think we should focus first on just building locally with Nix and leave CI changes for another PR(this would also help me in reviewing). The CI infra is a bit fragile and we depend on that for releases.

Cleanup of older setup would be good. The `create/destroy_test_db` always felt a bit convoluted. Though we should make sure that `with_tmp_db` works when testing on docker too.

**Comment by monacoremo** [comment]
@steve-chavez that makes sense - looking at the db logs, it was a race condition where cabal ran spec and spec-querycost in parallel and https://github.com/PostgREST/postgrest/blob/f6ce93f2c83178327ae42e5da42dd92a3f3742e2/test/QueryCost.hs#L25 does not hold - added a quick fix on the cabal side, but should probably be fixed properly at some point

**Comment by monacoremo** [comment]
> leave CI changes for another PR

@steve-chavez Absolutely, we should do this step by step - maybe even in a separate branch for now? Changing the stack resolver etc. is relatively intrusive...

**Comment by robx** [comment]
Oh, I missed that you were already working on updating stackage. #1484, 1485 are redundant with this one. But let's at least see if they pass CI.

**Comment by monacoremo** [comment]
> Oh, I missed that you were already working on updating stackage. #1484, #1485 are redundant with this one. But let's at least see if they pass CI.

@robx you did a much cleaner job with the dependencies! Let's get your work merged and I'll rebase this pull request.

**Comment by monacoremo** [comment]
@steve-chavez the style tests previously failed probably because stack ran out of memory when installing hlint and stylish-haskell - The latest commit makes the install more efficient by installing them directly from Nix. Happy to split that into a separate PR if you prefer.

**Comment by steve-chavez** [comment]
@monacoremo I'll give your PR a review now!

Btw, in case anyone stumbles with this error:
```
Downloading lts-15.8 build plan ...
RedownloadInvalidResponse Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-15.8.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 "/home/steve-chavez/.stack/build-plan/lts-15.8.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}
, responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Type","text/plain; charse
t=utf-8"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),("Strict-Transport-Security","max-age=315
36000"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("Via","1.1 varnish (Varnis
h/6.0)"),("X-GitHub-Request-Id","096A:7607:2850F0:2B45D6:5E9B3127"),("Accept-Ranges","bytes"),("Date","Sat, 18 Apr 2020 16:56:07 GMT"),(
"Via","1.1 varnish"),("X-Served-By","cache-gru17141-GRU"),("X-Cache","HIT, MISS"),("X-Cache-Hits","2, 0"),("X-Timer","S1587228968.876053
,VS0,VE119"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","fb7848c985ee0cb57ce6c6
e113b735c611e7372a"),("Expires","Sat, 18 Apr 2020 17:01:07 GMT"),("Source-Age","0")], responseBody = (), responseCookieJar = CJ {expose
= []}, responseClose' = ResponseClose})
``` 
The fix is to upgrade `stack`. See https://stackoverflow.com/a/57521914/4692662.

**Comment by steve-chavez** [comment]
> @steve-chavez the style tests previously failed probably because stack ran out of memory when installing hlint and stylish-haskell - The latest commit makes the install more efficient by installing them directly from Nix. Happy to split that into a separate PR if you prefer.

@monacoremo Please do, would be easier for me to review changes to CI in another PR(I do note that the build is faster, but I'll have to give the change more thought). It's weird why CircleCI is not picking the cache on that `style` job though. The `stack.yaml` hasn't changed.

I'll see if the style CI job has a fix. If not, I can merge without fixing that here. We'll just let it fail for now.

**Comment by monacoremo** [comment]
Will do - I'll submit the changes in smaller PRs. This here was good to figure out an overall structure that works, but it combined too many different concerns in one go.

#1489 should contain the bare necessities and I'll suggest additional improvements from there. I'll keep this PR as is for reference.

**Pull request closed without merging**
