### PR TITLE
chore: include base v4.17 to support ghc 9.4

### LINKED ISSUE #3107: Support ghc 9.4
The bounds for `base` in `postgrest.cabal` should include 4.17 so that GHC 9.4 is supported.

### PR DESCRIPTION
**Pull request by laurenceisla**
Closes #3107

### CODE REVIEW

**Comment by laurenceisla** [comment]
It looks like other libraries need to be updated too:

- `base` needs 4.17
- `text` needs at least `2.0.1` due to needing `ghc-prim 0.9` (possibly breaking update).
- `fuzzyset` needs `0.2.4`  due to needing `text`

I'm closing for now since it would take me some more time to test this. Anyone who wishes to continue feel free to take it.

**Comment by steve-chavez** [comment]
@laurenceisla I see CI passed this one. What was the issue?

**Comment by laurenceisla** [comment]
CI is using GHC 9.2, but it fails on GHC 9.4 (at least for me) so it wouldn't comply with that version... updating only `base` won't do much, I think.

**Comment by laurenceisla** [comment]
#3112 validates the errors when building with GHC 9.4.4 https://github.com/PostgREST/postgrest/actions/runs/7211356805/job/19646613918?pr=3112#step:7:16

**Pull request closed without merging**
