### PR TITLE
Release 6.0.1

### PR DESCRIPTION
**Pull request by steve-chavez**
I'm inclined to do a new PATCH release since the previous release process failed badly.

Windows was not possible to build with v6.0.0 and I had to use a different GHC and libraries to successfully compile and add a binary to the releases page(which doesn't seem correct).

Also the `text/html` feature(actually a bug for most users I'm sure) introduced in https://github.com/PostgREST/postgrest/issues/1308 was fixed and removed in https://github.com/PostgREST/postgrest/pull/1349. I'd like to properly document v6.0 without that.

I want to call this release a `v6.0.1` instead of `v6.1.0` because I want to communicate the release is more of a PATCH, despite there being 2 new features.

### CODE REVIEW

**Comment by steve-chavez** [comment]
Also going to make sure the release process works fine in my own repo this time.

**Comment by steve-chavez** [comment]
Damn. `build-prof-test` is failing consistently :disappointed:. It's the [same out of memory error I got on windows](https://github.com/PostgREST/postgrest/issues/1334#issuecomment-509731567) when compiling `QueryBuilder`. Release will fail again unless this is fixed.

I don't think it can be fixed by some config on GHC/stack. Maybe the easiest way would be integrating https://github.com/PostgREST/postgrest/pull/1286.

**Comment by steve-chavez** [comment]
Regarding limiting GHC memory usage, I got an answer on freenode: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/runtime_control.html#rts-flag--M%20%E2%9F%A8size%E2%9F%A9

However, as I was told and from my understanding from that doc, this won't stop GHC from crashing, it just prevents it from eating all your system memory.

**Comment by diogob** [comment]
Hi @steve-chavez , I have tried to reproduce the issue in a branch on my repo and got a [green test on circle](https://circleci.com/gh/diogob/postgrest/tree/release-6.0.1)! This might be some transient issue.

**Comment by steve-chavez** [comment]
Hey @diogob, thanks a lot for the notice! I retried the circle job and this time it went green :green_apple: .

**Comment by steve-chavez** [comment]
I've confirmed the release works in my repo https://github.com/steve-chavez/postgrest/releases/tag/v6.0.1.

Merging..

**Pull request merged**
