### PR TITLE
Bumps to v8.0.0

### LINKED ISSUE #1779: New Release ?
Hi,

Is there any chance getting a new release? (8.0.0 or 7.1.0 or 7.0.2 ?)
_( there are many fixes since May 2020 )_

Thank you.

### PR DESCRIPTION
**Pull request by steve-chavez**
Closes #1779.

- Correct/organize the CHANGELOG
- Bumps to v8.0.0

### CODE REVIEW

**Comment by steve-chavez** [comment]
Travis is not working anymore. This is showing on the account:

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

I've upgraded to a paid plan([1 concurrent job Plan](https://travis-ci.com/plans)) but that doesn't seem to be working. I now get a `Owner PostgREST does not have enough credits` when trying to trigger a new build.

Maybe we'll have to change to Circle for building MacOS binaries.

**Comment by steve-chavez** [comment]
Not sure why the [release step failed on CircleCI](https://app.circleci.com/pipelines/github/PostgREST/postgrest/1083/workflows/040c7a97-2371-4c66-8064-49e588b07492/jobs/9457), the docker tags where uploaded successfully([ref](https://hub.docker.com/r/postgrest/postgrest/tags?page=1&ordering=last_updated)).

**Comment by monacoremo** [comment]
> Not sure why the [release step failed on CircleCI](https://app.circleci.com/pipelines/github/PostgREST/postgrest/1083/workflows/040c7a97-2371-4c66-8064-49e588b07492/jobs/9457), the docker tags where uploaded successfully([ref](https://hub.docker.com/r/postgrest/postgrest/tags?page=1&ordering=last_updated)).

Yes, weird - will try to reproduce with another dockerhub repo.

It doesn't seem to have updated the description on Dockerhub to the latest version after 
https://github.com/PostgREST/postgrest/pull/1691: https://raw.githubusercontent.com/PostgREST/postgrest/main/nix/tools/release/docker-hub-full-description.md (note: does not contain the config file anymore)

**Comment by laurenceisla** [comment]
> Travis is not working anymore. This is showing on the account:
> 
> > Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

I've checked my TravisCI account and it looks like I may be responsible for that. Didn't know that the credit was for the whole team (looks like it is that way). All my branch builds consumed credit according to my usage activity. That may be the reason.

2021-07-26-130628_820x589_scrot

**Comment by steve-chavez** [comment]
> Issue seems to be with the final part of the script, which does not get excecised with nightly tags:

Ah, I see, that needs to be corrected then. Thanks for digging into this @monacoremo. 

> I've checked my TravisCI account and it looks like I may be responsible for that. Didn't know that the credit was for the whole team (looks like it is that way)

@laurenceisla :O That's surprising!

It seems CircleCI is also using a similar credit model now. We have few credits left for this week:

2021-07-26-173935_928x492_scrot

I think the right move here would be upgrading the CircleCI plan(to the [performance plan](https://circleci.com/pricing/)) and move our macOS testing/building there. It makes more sense to invest on Circle than Travis since we use it much more(Travis is only used for building the macOS binary).

**Pull request merged**
