### PR TITLE
Refactor dbStructure.hs

### PR DESCRIPTION
**Pull request by wolfgangwalther**
Related to #1719.

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
I moved the `parseArgs` part to SQL now. This does:
- increase coverage, because it avoids some edge cases in the parsers
- allow fool-proof parsing of argument names and types with spaces
- have the following side-effect:
  For functions without arguments, the schema cache seemed to store a single unnamed / untyped argument before:
  ```yaml
  - - qiName: welcome
      qiSchema: test
    - - pdArgs:
        - pgaName: ''
          pgaReq: true
          pgaType: ''
          pgaVar: false
        pdDescription: null
        pdHasVariadic: false
        pdName: welcome
        pdReturnType:
          contents:
            contents:
              qiName: text
              qiSchema: pg_catalog
            tag: Scalar
          tag: Single
        pdSchema: test
        pdVolatility: Volatile
  ```
  taken from https://github.com/PostgREST/postgrest/pull/1699/files#diff-153d54c3e6049f5c3ce9a68a92a10ccebd625e4ed7f13e2a51f908ae52aab1cbR60-R78

  Now, the schema cache has an empty `pdArgs` in that case. This might be related to some of the bugs we still have with overloading RPCs, although I didn't test that, yet. In any case the schema dump yaml files will become shorter ;).

**Comment by wolfgangwalther** [comment]
memory tests have been failing in CI for this PR. I have no idea why - my local build is well short of the thresholds:

```
ok 1 - POST /rpc/leak?columns=blob: with a json key of 1M the memory usage(9,728,264 bytes) is less than 13M
ok 2 - POST /leak?columns=blob: with a json key of 1M the memory usage(9,798,432 bytes) is less than 13M
ok 3 - PATCH /leak?id=eq.1&columns=blob: with a json key of 1M the memory usage(9,701,448 bytes) is less than 13M
ok 4 - POST /rpc/leak?columns=blob: with a json key of 10M the memory usage(37,459,200 bytes) is less than 41M
ok 5 - POST /leak?columns=blob: with a json key of 10M the memory usage(37,537,168 bytes) is less than 41M
ok 6 - PATCH /leak?id=eq.1&columns=blob: with a json key of 10M the memory usage(37,439,024 bytes) is less than 41M
ok 7 - POST /rpc/leak?columns=blob: with a json key of 50M the memory usage(160,678,984 bytes) is less than 171M
ok 8 - POST /leak?columns=blob: with a json key of 50M the memory usage(160,754,392 bytes) is less than 171M
ok 9 - PATCH /leak?id=eq.1&columns=blob: with a json key of 50M the memory usage(160,663,608 bytes) is less than 171M
ok 10 - POST /perf_articles?columns=id,body: with a json payload of 32K that has 1000 array values the memory usage(6,828,480 bytes) is less than 11M
ok 11 - POST /perf_articles?columns=id,body: with a json payload of 329K that has 10000 array values the memory usage(7,721,816 bytes) is less than 11M
ok 12 - POST /perf_articles?columns=id,body: with a json payload of 3.4M that has 100000 array values the memory usage(17,046,840 bytes) is less than 21M
```

**Comment by wolfgangwalther** [comment]
Memory seems to be fine in CI again.

A lot of the refactor is just about simplifying some pattern matches. Easier to read - less stale patterns that are not covered.

**Review by steve-chavez — APPROVED** [review]
LGTM!

Really like the parseArgs in SQL and the new addM2MRels is short and sweet :candy: .

**Pull request merged**
