### PR TITLE
Vendor orphaned configuration dependencies critbit and configurator-ng

### PR DESCRIPTION
**Pull request by robx**
To get unstuck on these orphaned and stale dependencies, I suggest bundling them with PostgREST as an intermediate step. This will allow easily updating them to build with newer GHC/base versions, and kicking them back out once a better alternative is found.

### CODE REVIEW

**Comment by robx** [comment]
Some open questions:
- cut the embedded libraries down to the minimum that's used by PostgREST?
- should I add fixes for new GHC to the code directly? (I'm not quite sure how to deal with unused import warnings for Semigroup/Monoid across GHC versions)
- I added the original LICENSE files (witih copyright info updated from the cabal files) within deps; should something be done at top-level?

**Comment by steve-chavez** [comment]
@robx Totally get why we need more control over those dependencies, as they seem unmaintained.

But instead of bundling them in this repo(5k lines added, big impact in the codebase), couldn't we have them forked and then published to hackage(with different names, like pgrst-critbit or smth) so we can instead reference them?

**Comment by ruslantalpa** [comment]
Or without publishing to hackage and just referencing the git

https://stackoverflow.com/questions/38377521/haskell-stack-install-package-dependency-from-github

**Comment by ruslantalpa** [comment]
Could be a repo under postgrest org in github

**Comment by robx** [comment]
Sure that would work for me too. I don't particularly care either way, just wanted to help make progress. And the advantage with this approach is that we see integration test results. :)

(Also it seemed like a less invasive change than putting up a fork of a deprecated package on hackage that's meant to be abandoned again soon.)

If it's really just the impact on the repository, I'm happy to cut it down to size. If there's some way I can help with the forking/uploading, I'm also happy to do that.

**Comment by steve-chavez** [comment]
> (Also it seemed like a less invasive change than putting up a fork of a deprecated package on hackage that's meant to be abandoned again soon.)

@robx You're right about hackage. Just forking and referencing git as Ruslan suggested would be better.

**Comment by robx** [comment]
Referencing a git revision in a local stack.yaml or whatever build file you use is all well and good, but doesn't do anything about the fact that postgrest isn't buildable from hackage with recent ghc versions.

Then you might as well deprecate it on hackage and note that you should get binary/source releases from the github repo / project homepage, no?

My personal motivation here is that I'd like to get postgrest built in nix/guix, and while it's possible to work around such issues there, it would be much more straightforward and clean to build directly from hackage. (As an aside, it would also give less of a stale impression if postgrest were buildable out of the box with recent ghc versions; I know it's actively maintained, but still.)

**Comment by robx** [comment]
Tell you what though, I'll give reimplementing the config parser a shot, seems like a fun exercise.

**Comment by ruslantalpa** [comment]
I a not opposed to having a postgrest specific config parser since we don't require a complicated logic or fancy features and while it seems a bit like reinventing the weel, it's a good tradeof to have postgrest easely bildable/installable.
having these features seems enough to me for any future uses:
- `key = value` `key=value` `key="value with spaces"` basic structure
- support comments with `#`
- `key=@file` read the value from file
- key=$(ENV_VAR)
- `key.sub1=a` `key.sub2=b` a map


this is a good overview of what's being used now https://github.com/PostgREST/postgrest/blob/master/docker/postgrest.conf

other oppinions?

**Comment by Qu4tro** [comment]
I've already gave my opinion on #1292 and I still have the same concern, but I'll expand them a bit.
I understand the motivation for reducing dependencies. I think #1304 is great! Yes, dependencies either get stale or get upgraded and have backwards-compatibility issues. I definitely can't say for certain that it won't happen to any package we add. On the other hand, we're responsible for more code that can go wrong. 

I think any approach that will fix the build is a good one at the moment. Either the upload of the fixed version to hackage (has anyone emailed the mantainers?) or the in-house implementation of it. So no objection on my part.

Still I think a bit more long term (after have builds working, after adding deprecation warnings, after adding migration options), we should stay away from a "simple", ad-hoc configuration file. I definitely don't agree that it's great for future use.
To be clear, when I mention `dhall` I'm trying to advocate to depend on a standardized configuration language. It's just that is one of the few that fit the bill. It also has the advantage of being available on stackage and hackage. I understand that `dhall` is full of fancy features that are not needed for pgrst, but reading environmental variables and mostly reading from files are not common features either.
The advantages of the use of a standardized config language are numerous. Editor syntax files (a big red warning if you mess up), tools can be more easily built to manipulate configuration files, instead of trying to provide an almost perfect printer/parser for the ad-hoc version (which is kind of nice, if you have to administrate +20 servers - even if they're not all pgrst) and well.. less code.

Anyway, that's my opinion.

**Comment by Qu4tro** [comment]
I assume no one yet has emailed the maintainers of configurator-ng for the lack of responses.
I'll send one later tonight.

**Comment by robx** [comment]
Closing in favor of #1312

**Pull request closed without merging**
