### PR TITLE
Move Linux, Windows and MacOS CI/CD to Github Actions

### PR DESCRIPTION
**Pull request by monacoremo**
Now that Travis and CircleCI impose capacity limits, it's probably easiest for us to run everything on Github Actions.

## Progress on feature parity with legacy CI

- [x] Build static Linux executable and Docker image with Nix
- [x] Build MacOS executable with Stack
- [x] Build Windows executable with Stack
- [x] Build FreeBSD executable - Options:
  - [x] keep CirrusCI for now - how to best get binary into release?
    - went for this: Configured CirrusCi to save the build as an artifact and wrote a script to get that artifact in the release job
  - use a hack and run a FreeBSD VM on a Github Actions MacOS runner
    - decided against this, too hacky. The freebsd-vm uses a pre-cooked vm image that I can't jnspect
- [x] Run linter & style check
- [x] Run tests with Nix
  - [x] Colors in output - GitHub Actions limitation, does not provide a TTY; hack from https://github.com/actions/runner/issues/241#issuecomment-842566950 `shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'` - used only for the Nix tests for now
  - [x] Run all tests, even if one fails
  - Cache cabal - not needed, quick enough (< 5 min)
- [x] Build and run tests with Stack on Linux
  - Run memory tests - don't think this is needed as we run those with Nix
- [x] Upload coverage
- Release nightlies - might not be needed as we can publish artifacts with each CI run? tbd
  - replaced by:
    - Bleeding edge available through artifacts saved for each check run
    - Pre-releases (e.g. 9.0.0-a1, -b4 etc. for alphas and betas) automatically released and pushed to Docker Hub when tagged
- [x] Actual releases

## Extra

- [x] Run tests on MacOS
- [x] Release only if builds for all platforms succeeded
- [x] No secrets required on CirrusCI
- [x] Added a simple release script to tag and trigger a release - just set the right version in `postgrest.cabal`, commit and run `.github/release`
- [x] Switched the FreeBSD build from cabal-install to Stack for consistency (same GHC, libraries etc. as all other builds) 

Not for this PR:

* Build Linux Arm executable - same as FreeBSD or with self-hosted runner

## Tasks before merge

- [x] Set Codecov token
  - [ ] Probably not needed as Wolfgang pointed out, let's remove it
- [ ] Set CACHIX_AUTH_TOKEN secret
- [ ] Set DOCKER_PASS secret (is `postgrest-bot` the right user name?
- [ ] Disable CircleCI on this repo
- [ ] Disable Travis on this repo
- [ ] Disable Appveyor on this repo

### CODE REVIEW

**Comment by monacoremo** [comment]
@steve-chavez Do we need to enable Github Actions in the settings?

**Comment by steve-chavez** [comment]
> Do we need to enable Github Actions in the settings?

Just checked, they're enabled.

> Upload coverage - requires token

Will set this.

**Comment by monacoremo** [comment]
> > Do we need to enable Github Actions in the settings?
> 
> Just checked, they're enabled.

Hm, it doesn't trigger for this PR somehow.. Are the settings set like this?

* Actions permissions: ``Allow all actions`?
* Fork pull request workflows from outside collaborators: `Require approval for first-time contributors`?
* Workflow permissions: `Read repository contents permission` would be preferrable

**Comment by steve-chavez** [comment]
> Hm, it doesn't trigger for this PR somehow.. Are the settings set like this?

Yes, screenshot:

res

**Comment by steve-chavez** [comment]
Hm, still not triggering I see. Maybe it's because of the draft PR?

**Comment by monacoremo** [comment]
Ah, here we go - apparently had to disable GH Actions in my fork. Thank you @steve-chavez !

**Comment by monacoremo** [comment]
First successful run: 

image

Note: With the hot cache we have now the Stack builds are just 1-3 minutes.

We now have executable for each OS available as artifacts for each push, see the list at the bottom. I think this could supercede our `nightly` setup - WDYT @steve-chavez ? Only thing to potentially change would be to patch the version in `postgrest.cabal` if there is no tag.

**Comment by steve-chavez** [comment]
> I think this could supercede our nightly setup - WDYT @steve-chavez ? Only thing to potentially change would be to patch the version in postgrest.cabal if there is no tag.

Hm, I do see there's some overlap with how we do the nightlies. But having all of them on the same [release page](https://github.com/PostgREST/postgrest/releases/tag/nightly) feels more convenient, each nightly can also point to its changelog. How would we instruct users to use nightlies with this new way?

**Comment by monacoremo** [comment]
> Hm, I do see there's some overlap with how we do the nightlies. But having all of them on the same release page feels more convenient, each nightly can also point to its changelog. How would we instruct users to use nightlies with this new way?

Let me try!

1. If you want to test the latest unreleased features, go to image, pick a recent green build and download the artifact for your platform. To see what changed, follow the linked PR/commit and look at the Changelog
2. If you want to test a specific unreleased change, klick the green CI indicator on the respective PR/commit, go to the CI action and download the artifact for your platform

Case (1) is a different place to look at, but I don't think it would be too much for powerusers that want to test unreleased features. And we aim to release more often anyway :-) 

Case (2) is not even possible right now

**Comment by wolfgangwalther** [comment]
> > Upload coverage - requires token
>
> Will set this.

I don't think we need a token here. At the [codecov-action repo](https://github.com/codecov/codecov-action) it says:

> For public repositories, no token is needed

**Comment by monacoremo** [comment]
> I don't think we need a token here. At the [codecov-action repo](https://github.com/codecov/codecov-action) it says:
> 
> > For public repositories, no token is needed

Ah, good catch - will try without

**Comment by monacoremo** [comment]
Apparently `with_tmp_db` was portable all along! Spec tests now also run on MacOS 🎉

**Comment by steve-chavez** [comment]
> If you want to test the latest unreleased features, go to image, pick a recent green build and download the artifact for your platform. To see what changed, follow the linked PR/commit and look at the Changelog

Ah, I forgot. We have to consider docker as well, we were also releasing [nightlies there](https://hub.docker.com/r/postgrest/postgrest/tags?page=1&ordering=last_updated).

**Comment by monacoremo** [comment]
@steve-chavez This new setup now works pretty well!

With hot caches, a full CI run takes 5-10 minutes, including all tests as well as the builds for Linux, Windows, MacOS and FreeBSD. 

Build artifacts for all platforms are available for every single commit, also from pull requests. I believe this covers most of the need for the 'nightly' release (which was quite inconsistent so far). To replace it, my suggestion is:

* For bleeding edge builds (e.g. testing whether a commit fixed an issue), direct users to the respective CI build. The Docker image can be imported with `docker load -i ...`
* For intermittent updates, use pre-releases such as '8.0.1-a1' or '9.0.0-b2' etc.) - these get released on GitHub as pre-releases and tagged on Docker Hub, leaving 'latest' untouched
* For proper releases, do full releases on GitHub and also push to 'latest' on Docker Hub 

The workflow enforces that the tagged version corresponds to the version in `postgrest.cabal` before releasing. This way, pre-releases will have a proper version, without the approach of patching the cabal file, which breaks caches and is a bit messy imo)

WDYT?

**Comment by steve-chavez** [comment]
@monacoremo Looks amazing! Great work! :100: :1st_place_medal:

> for the 'nightly' release (which was quite inconsistent so far).
> without the approach of patching the cabal file, which breaks caches and is a bit messy imo)

True, the nightlies were more of a hack. Let's go ahead with your approach :+1:

**Review by steve-chavez — APPROVED** [review]

**Comment by monacoremo** [comment]
> @monacoremo Looks amazing! Great work! 💯 🥇

Thank you, glad to hear! :-) 

I've tested the release steps on my https://github.com/monacoremo/postgrest fork, both pre-releases and full releases. 

@steve-chavez I've noted the last todos that need to be completed by you as the repo owner above: 

- [x]  Set Codecov token
  - [ ]  Probably not needed as Wolfgang pointed out, let's remove it
- [ ]  Set CACHIX_AUTH_TOKEN secret
- [ ]  Set DOCKER_PASS secret (is postgrest-bot the right user name?
- [ ]  Disable CircleCI on this repo
- [ ]  Disable Travis on this repo
- [ ]  Disable Appveyor on this repo

Would you be able to make those changes and then we merge?

**Comment by steve-chavez** [comment]
> Would you be able to make those changes and then we merge?

@monacoremo Sure. Done!

Also, I've revoked the secrets and Github apps that Appveyor and Travis had(CircleCI still has an installed app on the org because we use it on postgrest-docs).

> is postgrest-bot the right user name?

I don't have the postgrest-bot creds anymore(it was created using begriffs' account), so it should be changed to my username "stevechavez". I've confirmed it works, I used it for v8.0.

**Comment by steve-chavez** [comment]
@monacoremo Do you know what's the state of building the static binary with Nix on ARM? It didn't work last time [we tried](https://github.com/PostgREST/postgrest/issues/1117#issuecomment-606325555).

Ideally we'd build the ARM binary on Github Actions. Currently I build the ARM binary manually for Ubuntu.

**Comment by monacoremo** [comment]
I think that's going to be quite tricky - but let's try it! Do you have a machine that we can use for testing @steve-chavez ?

On the Nix side, I dont think that https://github.com/nh2/static-haskell-nix that we rely on actively tracks whether ARM-builds succeed. But it could work in principle and we could be lucky, let's see! A full alternative would be to use https://input-output-hk.github.io/haskell.nix/tutorials/cross-compilation/ instead of the standard Nix setup, but that would be a major undertaking.

On the GitHub Actions side, I don't think there is an ARM runner right now... We would need to host an external runner.

**Comment by steve-chavez** [comment]
> Do you have a machine that we can use for testing @steve-chavez ?

I do! I use a t4g.large on AWS to build the Ubuntu binary. I'll grant you access and share you the details through email :email:

**Pull request merged**
