### PR TITLE
Update hasql usage

### PR DESCRIPTION
**Pull request by bgamari**
Move to hasql 1.3, hasql-transaction 0.7, and hasql-pool 0.5. This is largely mechanical.

### CODE REVIEW

**Comment by bgamari** [comment]
Note that I am still testing this but this has made it possible to build postgrest under nix, which was previously extremely painful.

**Comment by steve-chavez** [comment]
Seems is working good(test suite green) after a rebase and adding these to `stack.yaml`:
```yaml
- hasql-1.3
- hasql-pool-0.5
- hasql-transaction-0.7
- text-builder-0.5.1.1
```
I'll merge after that's done.

**Comment by YoEight** [comment]
Hello, any news of this MR as those packages update will be appreciated. Thanks for your time!

**Comment by steve-chavez** [comment]
I've added this commit and rebased it in #1185.

**Pull request closed without merging**
