### PR TITLE
Allow base64-bytestring 1.2 and optparse-applicative 0.16

### PR DESCRIPTION
**Pull request by robx**
Relax some bounds for stackage, compare https://github.com/commercialhaskell/stackage/issues/5598 and https://github.com/commercialhaskell/stackage/issues/5597

### CODE REVIEW

**Comment by robx** [comment]
@steve-chavez Would you apply the version updates for base64-bytestring and optparse-applicative (first commit) as a Hackage revision?

I'm working on getting hasql-notifications added for the next release (see https://github.com/diogob/hasql-notifications/issues/5), but it'd be great to get these updates in sooner.

**Comment by steve-chavez** [comment]
> Would you apply the version updates for base64-bytestring and optparse-applicative (first commit) as a Hackage revision?

@robx Done! Check https://hackage.haskell.org/package/postgrest-7.0.1/revisions.

**Comment by steve-chavez** [comment]
PR looks good. Should I merge now or do you expect to add more changes here(hasql-notifications)?

**Comment by robx** [comment]
Awesome, thank you, that was fast! Should be good to merge, don't expect more changes to be needed regarding hsql-notifications.

**Pull request merged**
