### PR TITLE
Dump config through Admin API implementation

### PR DESCRIPTION
**Pull request by SkyWriter**
This is a work-in-progress implementation of https://github.com/PostgREST/postgrest/issues/3171.

### CODE REVIEW

**Comment by steve-chavez** [comment]
@SkyWriter The direction looks good. Thanks for the contribution!

The Admin API uses python tests, you can get some inspiration from these:

https://github.com/PostgREST/postgrest/blob/6682baebd21253ebb851d8c58548982736bc0714/test/io/test_io.py#L635-L658


Then you can run them locally with:

```bash
$ nix-shell

$ postgrest-test-io

# you can also choose to run one test with
# $ postgrest-test-io -k name_of_test
```

**Comment by Almaani41** [comment]
Network:.txt
<https://drive.google.com/file/d/1-aCTP_uWnR7DjNrDiYYLRw6kxpUB5Cyw/view?usp=drivesdk>


في الاثنين، ٢٩ كانون الثاني ٢٠٢٤, ١٠:٣٤ م Steve Chavez <
***@***.***> كتب:

**Comment by SkyWriter** [comment]
@steve-chavez Thank you for the feedback. I think the PR is ready for review. "Loadtest / Loadtest PR (Nix) (pull_request)" automatic check is failing, but this seems to be rather just a CI issue. Let me know if you deem any changes are needed. Otherwise, thanks for running the wonderful project!

**Review by steve-chavez — APPROVED** [review]
Great work! And yes, the loadtest failure is unrelated. Let's merge :rocket:

**Pull request merged**
