### PR TITLE
postgrest.cabal: fix constraints on protolude and hasql-transaction

### PR DESCRIPTION
**Pull request by ilovezfs**
Fixes https://github.com/PostgREST/postgrest/issues/1110.

### CODE REVIEW

**Comment by ilovezfs** [comment]
@begriffs @steve-chavez any thoughts?

**Comment by steve-chavez** [comment]
Seems ok, thanks. One question though why when using `cabal` the build fails and not when using `stack`?

**Comment by ilovezfs** [comment]
You have them pinned for stack:
https://github.com/PostgREST/postgrest/blob/master/stack.yaml#L8
https://github.com/PostgREST/postgrest/blob/master/stack.yaml#L11

**Comment by steve-chavez** [comment]
Forgot that, all good. Merging.

**Comment by ilovezfs** [comment]
Thanks!

**Pull request merged**
