### PR TITLE
Introduce ServerTiming for queries

### PR DESCRIPTION
**Pull request by develop7**
Roadmap:

- [ ] `db` — database response time
- [ ] `render` — resultset render time
- [ ] `plan` — :question: :question: :question: do we need it? is it worth it? does it get stuck?
- [x] `jwt` — authentication time

quoting https://github.com/PostgREST/postgrest/issues/2771#issuecomment-1696590401:
> For now I'm thinking of the following steps, the main idea is to make the Response and Query modules pure; this will also enable those to be "doctested":
> 
* [x]  Make the Response module pure (wip on [steve-chavez@edbc4f9](https://github.com/steve-chavez/postgrest/commit/edbc4f92ad51b7c672251e6d9d1269caaad61bd5))
* [ ]  Make the Query module pure
	* This will also help implement [Feature request: show SQL query in terminal(log-level=debug) #1578 (comment)](https://github.com/PostgREST/postgrest/issues/1578#issuecomment-1705737599)
	* The Query module has functions, like `failNotSingular`, that are impure in nature (they need to rollback), these can be separated into another `AbortQuery` module.
* [ ]  Then have a single function entrypoint for each module.

### CODE REVIEW

**Comment by develop7** [comment]
hey @steve-chavez do we need to make `Response.info{Ident,Info,Proc}Response` pure as well? My guess is we do, but not right now

https://github.com/PostgREST/postgrest/blob/a6e3eda5b20817f134beb8d660029bd2875c280f/src/PostgREST/Response.hs#L194-L214

**Comment by steve-chavez** [comment]
Hey @develop7, yeah so `infoIdentResponse` is the response for the OPTIONS method and this one is special because it doesn't have a Plan or Query stage - it doesn't execute any query.

Hm, maybe it's not that relevant for `Server-Timing` but I think it would be good to have it pure for completion and consistency.

**Comment by steve-chavez** [comment]
>  plan — ❓ ❓ ❓ do we need it? is it worth it? does it get stuck?

Yeah, so during [resource embedding](https://postgrest.org/en/stable/references/api/resource_embedding.html) I believe the plan could get slow. If that's true then we might try to optimize the code or cache the results somehow ([idea here](https://github.com/PostgREST/postgrest/issues/2816)).

But first we would need to confirm if that is indeed the case.

**Comment by steve-chavez** [comment]
Might make sense to combine both the `ApiRequest.userApiRequest` and the Plan module work into the same `Server-Timing` duration too.

**Comment by develop7** [comment]
Gotchu, on it

**Comment by steve-chavez** [comment]
@develop7 The current refactor seem good to merge. Maybe you'd like to open another PR for that and leave this one open as sort of an "epic"?

Otherwise you'll have to rebase each time the Response module is modified, that's currently happening on https://github.com/PostgREST/postgrest/pull/2969/

**Comment by develop7** [comment]
> it doesn't execute any query

Hmm, that means we need to make the `db` timing optional at least here, which requires all/some metrics to be optional. 

I'm wondering if we could get away with something like 

```haskell
data ResponseTiming =  RMJwt | RMRender | RMDb

data ServerTimings = Map ResponseTiming Double
```

then pass the value of ServerTimings along, throwing metrics' values in as needed; then render the header somewhere near our newly introduced `pgrstResponse`, wrapper around WAI.Response. That should enable us to add extra metrics relatively easily.

What do you guys think?

**Comment by develop7** [comment]
> Maybe you'd like to open another PR for that and leave this one open as sort of an "epic"?

Good point, let me shuffle commits a bit then.

**Comment by steve-chavez** [comment]
> Hmm, that means we need to make the db timing optional at least here, which requires all/some metrics to be optional.

True.

> That should enable us to add extra metrics relatively easily.
> What do you guys think?

@develop7 Sounds good!

**Comment by develop7** [comment]
> Good point, let me shuffle commits a bit then.

Shuffling done, the PR got accidentally closed though

**Pull request closed without merging**
