### PR TITLE
Allow aeson 1.5

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass here.

### CODE REVIEW

**Comment by steve-chavez** [comment]
LGTM :+1:

**Comment by robx** [comment]
Thanks for this! The relevant stackage tracking ticket: https://github.com/commercialhaskell/stackage/issues/5393

@steve-chavez I wonder if we could make a cabal revision with this change on hackage relaxing this bound in version 7.0.1, since no source-level change seems involved?

**Comment by steve-chavez** [comment]
Hey @robx. You mean [Hackage Metadata Revisions ](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md) right? I didn't know it was possible to update the dependencies bounds without a new release. I'm reading those docs now...(still not clear how to do the revision).

**Comment by steve-chavez** [comment]
Argh, I'm not seeing how to do the revision. @robx Do you have a guide on how to do it?

**Comment by robx** [comment]
Great, thanks! Haven't done this myself before, but happy to help try figure it out if it doesn't work.

**Comment by steve-chavez** [comment]
@robx Done! See: https://hackage.haskell.org/package/postgrest-7.0.1/revisions. Let me know if the change is good.

**Comment by robx** [comment]
Looks perfect, thanks!

**Pull request merged**
