### PR TITLE
Allow returning XML from single-column queries

### PR DESCRIPTION
**Pull request by fjf2002**
Somehow completing #2202

### CODE REVIEW

**Comment by fjf2002** [comment]
> Can you run `nix-shell --run postgrest-style`?
Well, no. I do not understand the `nix` stuff, cant get it to run. Are there any readmes?

**Comment by steve-chavez** [comment]
@fjf2002 Yes, there's a guide on https://github.com/PostgREST/postgrest/tree/main/nix#getting-started-with-nix

**Comment by fjf2002** [comment]
Sorry, https://github.com/PostgREST/postgrest/tree/main/nix#getting-started-with-nix does not help me. I have installed nix as ubuntu packages.
* all nix commands need sudo to run
* I have the error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
* Especially `sudo nix-shell --run postgrest-style` gives the error `fatal: not a git repository (or any of the parent directories): .git                                        
Couldn't find postgrest.cabal. Please make sure to run this command somewhere in the PostgREST repo.`. But I did run the command from my postgrest repo directory.


Any ideas?

**Comment by steve-chavez** [comment]
>I have installed nix as ubuntu packages.
> all nix commands need sudo to run

Hm, using the distro package is no good. Remove the distro package and try with the [multi-user installation mentioned here](https://nixos.org/download.html). 

For reference, I'm on PopOS and I don't need sudo for Nix.

**Comment by fjf2002** [comment]
@steve-chavez: Thank you for your support. I am getting better in handling haskell and its ecosystem.

**Pull request merged**
