### PR TITLE
Add autocompletion for postgrest-watch

### PR DESCRIPTION
**Pull request by monacoremo**
TIL bash autocompletion. Fixes one item of #1671

### CODE REVIEW

**Comment by wolfgangwalther** [comment]
That looks a bit... short!

I get the following error when using it: 

```
postgrest-watch postbash: completion: function `_command' not found
```

**Comment by wolfgangwalther** [comment]
That's even shorter! But it works... :D

**Comment by monacoremo** [comment]
Then let's go even shorter! (`-F _command` seems to be non-standard, by `-c` apparently works? https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html specifies it as alias to `-A command`)

**Comment by monacoremo** [comment]
We are going to have the most polished dev experience ever - no excuses now not to do many performance releases!

**Comment by wolfgangwalther** [comment]
haha :)
Absolutely!

( @steve-chavez your job with the performace! )

**Comment by wolfgangwalther** [comment]
So I'm pretty sure the pipeline fails is completely unrelated. Merging!

**Comment by wolfgangwalther** [comment]
I already used postgrest-watch yesterday and it's great!

**Pull request merged**
