### PR TITLE
LTS 13.29

### PR DESCRIPTION
**Pull request by diogob**
I've done some changes to the `circleci/config.yml` scripts to get a faster feedback loop when trying to tweak the build:
* Updated stack to 2.1.3
* Save the cache a bit earlier so we have usable cache even if the build or linting fails.
* Split the build steps into dependencies and main target so we can save the cache for the dependencies. 

I have also done some changes to the `QueryBuilder` module to avoid the out of memory issues, breaking the module into several smaller internal modules.

Also added the `stack.yaml.lock` which is a new feature in stack to improve build reproducibility (apparently this is really a word 😜 ).

@steve-chavez I have started my branch on top of your `release-6.0.1` branch (I was assuming that you would merge that one first). But let me know if you want me to remove those commits or rebase against some other branch.

Cheers!

### CODE REVIEW

**Comment by diogob** [comment]
Notice that the memory tests with `--profile` are also working on this branch: https://circleci.com/gh/diogob/postgrest/107

**Comment by steve-chavez** [comment]
Hey @diogob. Thanks a lot for your help.

I'm surprised that `lts-13-29` built successfully on appveyor since I got some issues earlier. Great idea on splitting the `QueryBuilder` module. 

I think it'd be better to merge your PR first because I managed to get another `build-prof-test` failure on https://github.com/PostgREST/postgrest/pull/1363.

Could you rebase against master? Then I'll give it another review.

**Comment by diogob** [comment]
@steve-chavez rebased on master

**Comment by steve-chavez** [comment]
LGTM! Thanks a lot for jumping in to help @diogob. Merging.

**Pull request merged**
