### PR TITLE
Include foreign tables in API description

### PR DESCRIPTION
**Pull request by rhyamada**
Added missed relkind for foreign table.

### CODE REVIEW

**Comment by begriffs** [comment]
Thanks, have you built this locally and confirmed that the foreign tables show up?

**Comment by rhyamada** [comment]
Yes, Foreign tables are correctly displayed I test only get methods.

**Comment by begriffs** [comment]
Cool! So how might we add a regression test to prevent this from breaking in the future? Maybe include a CSV file in our test fixtures and use [file_fdw](https://www.postgresql.org/docs/10/static/file-fdw.html) to access it as a table? Are you interested in giving that a try?

**Comment by begriffs** [comment]
@rhyamada want some suggestions about how to modify the test suite, or would you prefer I write the test?

**Comment by steve-chavez** [comment]
I'll add a test for this and merge it before next release.

**Comment by steve-chavez** [comment]
I don't see the foreign table in the OpenAPI description with this change, however if I add the change(`'f'`) to the `accessibleTables` query, I do see the foreign table showing.

**Comment by steve-chavez** [comment]
Closing this since #1101 got merged. Thanks @rhyamada.

**Pull request closed without merging**
